package br.ufmg.engsoft.urna.entities;

import java.util.HashMap;
import java.util.Map;
import java.util.List;
import java.util.Objects;

/**
 * The question type.
 */
public class Urna {
  /**
   * The id of the question.
   * When null, the id will be automatically generated by the database.
   */
  public final String id;
  /**
   * The theme of the question. Mustn't be null nor empty.
   */
  public final String theme;
  /**
   * The description of the question. Mustn't be null nor empty.
   */
  public final String description;
  /**
   * The statement of the question. May be null or empty.
   */
  public final String statement;
  /**
   * The record of the question per semester per class. Mustn't be null, may be
   * empty.
   */
  public final Map<Semester, Map<String, Float>> record;
  /**
   * Whether the question is private.
   */
  public final boolean pvt;
  /**
   * The type of the question, either open or multiple choice.
   */
  public final String type;
  /**
   * How many options the question have if the question is multiple choice.
   */
  public final String optCount;
  /**
   * The options in the multiple choice question.
   */
  public final List<String> options;

  /**
   * Builder for Question.
   */
  public static class Builder {
    protected String id;
    protected String theme;
    protected String description;
    protected String statement;
    protected Map<Semester, Map<String, Float>> record;
    protected boolean pvt = true;
    protected String type;
    protected String optCount;
    protected List<String> options;

    public Builder id(String id) {
      this.id = id;
      return this;
    }

    public Builder theme(String theme) {
      this.theme = theme;
      return this;
    }

    public Builder description(String description) {
      this.description = description;
      return this;
    }

    public Builder statement(String statement) {
      this.statement = statement;
      return this;
    }

    public Builder record(Map<Semester, Map<String, Float>> record) {
      this.record = record;
      return this;
    }

    public Builder pvt(boolean pvt) {
      this.pvt = pvt;
      return this;
    }

    public Builder type(String type) {
      this.type = type;
      return this;
    }

    public Builder optCount(String optCount) {
      this.optCount = optCount;
      return this;
    }

    public Builder options(List<String> options) {
      this.options = options;
      return this;
    }

    /**
     * Build the question.
     * 
     * @throws IllegalArgumentException if any parameter is invalid
     */
    public Urna build() {
      if (theme == null)
        throw new IllegalArgumentException("theme mustn't be null");

      if (theme.isEmpty())
        throw new IllegalArgumentException("theme mustn't be empty");

      if (description == null)
        throw new IllegalArgumentException("description mustn't be null");

      if (description.isEmpty())
        throw new IllegalArgumentException("description mustn't be empty");

      if (this.record == null)
        this.record = new HashMap<Semester, Map<String, Float>>();
      else
        // All inner maps mustn't be null:
        for (var entry : this.record.entrySet())
          if (entry.getValue() == null)
            throw new IllegalArgumentException("inner record mustn't be null");

      return new Urna(
          this.id,
          this.theme,
          this.description,
          this.statement,
          this.record,
          this.pvt,
          this.type,
          this.optCount,
          this.options);
    }
  }

  /**
   * Protected constructor, should only be used by the builder.
   */
  protected Urna(
      String id,
      String theme,
      String description,
      String statement,
      Map<Semester, Map<String, Float>> record,
      boolean pvt,
      String type,
      String optCount,
      List<String> options) {
    this.id = id;
    this.theme = theme;
    this.description = description;
    this.statement = statement;
    this.record = record;
    this.pvt = pvt;
    this.type = type;
    this.optCount = optCount;
    this.options = options;
  }

  /**
   * Equality comparison.
   * Although this object has an id, equality is checked on all fields.
   */
  @Override
  public boolean equals(Object obj) {
    if (obj == this)
      return true;

    if (!(obj instanceof Urna))
      return false;

    var question = (Urna) obj;

    return this.id.equals(question.id)
        && this.theme.equals(question.theme)
        && this.description.equals(question.description)
        && this.statement.equals(question.statement)
        && this.record.equals(question.record)
        && this.pvt == question.pvt
        && this.type == question.type
        && this.optCount == question.optCount;
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        this.id,
        this.theme,
        this.description,
        this.statement,
        this.record,
        this.pvt,
        this.type,
        this.optCount,
        this.options);
  }

  /**
   * Convert a Question to String for visualization purposes.
   */
  @Override
  public String toString() {
    var builder = new StringBuilder();

    builder.append("Question:\n");
    builder.append("  id: " + this.id + "\n");
    builder.append("  theme: " + this.theme + "\n");
    builder.append("  desc: " + this.description + "\n");
    builder.append("  record: " + this.record + "\n");
    builder.append("  pvt: " + this.pvt + "\n");
    builder.append("  type: " + this.type + "\n");
    builder.append("  optCount: " + this.optCount + "\n");
    builder.append("  options: " + this.options + "\n");
    if (this.statement != null)
      builder.append(
          "  head: " +
              this.statement.substring(
                  0,
                  Math.min(this.statement.length(), 50))
              +
              "\n");

    return builder.toString();
  }
}
